- name: Set up root password 
  debconf:
    name: "mariadb-server-{{ mariadb_version }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "password"
  changed_when: false
  no_log: true
  with_items:
    - question: 'mysql-server/root_password'
      value: '{{ mariadb_root_password }}'
    - question: 'mysql-server/root_password_again'
      value: '{{ mariadb_root_password }}'
  when: ansible_os_family == "Debian"
