- name: Copy systemctl file
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items: "etc/systemd/system/kestrel-jincreek-admin.service"

- name: Start kestrel-jincreek-admin.service 
  service:
    name: kestrel-jincreek-admin.service 
    enabled: yes

- name: Restart kestrel-jincreek-admin.service 
  service:
    name: kestrel-jincreek-admin.service 
    state: restarted
