FROM mcr.microsoft.com/dotnet/core/sdk:3.1

RUN echo "Start $(date)" \
  && apt update -y
RUN apt install -y \
  vim jq mariadb-client

RUN dotnet tool install --global dotnet-ef
ENV PATH $PATH:/root/.dotnet/tools

### Clean up...
RUN rm -rf /var/lib/apt/lists/*
