- name: Now
  command: date +"%Y%m%d%H%M"
  register: now

- name: debug
  debug:
    var: now.stdout

- name: Application Directory({{ now.stdout }})
  file:
    path: "{{ application_directory }}/Batch_{{ now.stdout }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy Script
  copy:
    src: batch.sh
    dest: "{{ application_directory }}/bin"
    mode: 0755
    owner: root
    group: root

- name: Nkf Script
  shell: nkf --overwrite -Lu {{ application_directory }}/bin/batch.sh

- name: Copy Assembly
  copy: 
    src: Batch.zip
    dest: "{{ item }}"
    mode: 0640
    owner: root
    group: root
  with_items: "{{ application_directory }}/Batch.zip"

- name: Unarchive Assembly
  unarchive:
    src: "{{ application_directory }}/Batch.zip"
    dest: "{{ application_directory }}/Batch_{{ now.stdout }}"
    remote_src: yes

- name: Create symbolic link
  file:
    src: "{{ application_directory }}/Batch_{{ now.stdout }}"
    dest: "{{ application_directory }}/Batch"
    state: link
